const MIN_AVATAR_NUMBER = 1;
const MAX_AVATAR_NUMBER = 1;

const DEFAULT_SCALE = 100;
const SCALE_STEP = 25;
const MAX_DESCRIPTION_LENGTH = 140;
const MAX_HASHTAGS_COUNT = 5;
const RANDOM_PICTURES_MAX = 10;

export const FILE_TYPES = ['jpg', 'jpeg', 'png'];

export const SCALE = {
  MIN: 25,
  MAX: 100
};

<<<<<<< HEAD
export {MIN_AVATAR_NUMBER, MAX_AVATAR_NUMBER, DEFAULT_SCALE, SCALE_STEP, MAX_HASHTAGS_COUNT, MAX_DESCRIPTION_LENGTH, RANDOM_PICTURES_MAX};
=======
export {MIN_AVATAR_NUMBER, MAX_AVATAR_NUMBER, DEFAULT_SCALE, SCALE_STEP, MAX_HASHTAGS_COUNT, MAX_DESCRIPTION_LENGTH};
>>>>>>> bfca8f2e3511ddbb6bb429c9847cccd5b9258d8e
