const MIN_AVATAR_NUMBER = 1;
const MAX_AVATAR_NUMBER = 1;

const DEFAULT_SCALE = 100;
const SCALE_STEP = 25;
const MAX_DESCRIPTION_LENGTH = 140;
const MAX_HASHTAGS_COUNT = 5;

export const SCALE = {
  MIN: 25,
  MAX: 100
};

export {MIN_AVATAR_NUMBER, MAX_AVATAR_NUMBER, DEFAULT_SCALE, SCALE_STEP, MAX_HASHTAGS_COUNT, MAX_DESCRIPTION_LENGTH};
